### ISSUE TITLE
IiDs of mocked merge requests are equal to the IDs

### ISSUE THREAD

**Issue by msrouchou** [ubisoft/NGitLab#168]
In a GitLab server, IDs and IiDs are different, but mocked merge requests do not mimic that behavior. 

Say you're creeating a mocked MR:
- The id is set using `mergeRequest.Id = Server: Interlocked.Increment(ref _lastMergeRequestId);`
  -> ID = 1
- The IiD however uses a different logic: `mergeRequest.Id = MergeRequestsCollection: Select(mr => mr.Iid).DefaultIfEmpty().Max() + 1;`
  -> IiD = 1

As a solution, we could just keep incrementing the ID.

**Comment by meziantou** [comment]
The behavior matches what GitLab does. If you create MRs in two different projects, both MRs will have Iid=1 but should have different Id. The Id is global, whereas Iid is per project.

That's being said, I think we should change the logic to help detect issues where the user uses Id instead of Iid.
I solution could be to set the initial Id to something different from 0 (e.g. `_lastMergeRequestId = 1000`)
